name: Build Gray Engine

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        target: [windows, html5]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Haxe
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.3.7

      - name: Install Haxelib dependencies
        run: |
          haxelib install lime 8.2.2
          haxelib install flixel 6.1.0
          haxelib install openfl 9.4.1
          haxelib run lime setup
          haxelib run lime setup flixel

      - name: Build Windows
        if: matrix.target == 'windows'
        run: haxelib run lime build windows

      - name: Build HTML5
        if: matrix.target == 'html5'
        run: haxelib run lime build html5

      - name: Upload artifacts (Windows)
        if: matrix.target == 'windows'
        uses: actions/upload-artifact@v4
        with:
          name: gray-engine-windows
          path: Export/windows/bin/**

      - name: Upload artifacts (HTML5)
        if: matrix.target == 'html5'
        uses: actions/upload-artifact@v4
        with:
          name: gray-engine-html5
          path: Export/html5/bin/**
